name: todo_sqflite_monorepo

repository: https://github.com/your-username/todo_sqflite

# fvmで管理されているFlutter SDKのパスを指定
# これにより、melos bootstrapもfvm経由で実行されます
sdkPath: .fvm/flutter_sdk

packages:
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: melos exec -- "fvm flutter analyze ."
    description: Run `flutter analyze` in all packages.

  format:
    run: melos exec -- "fvm dart format ."
    description: Run `dart format` in all packages.

  test:
    run: melos exec -- "fvm flutter test"
    description: Run `flutter test` in all packages.

  clean:
    run: melos exec -- "fvm flutter clean"
    description: Run `flutter clean` in all packages.

  get:
    run: melos exec -- "fvm flutter pub get"
    description: Run `flutter pub get` in all packages.

  version:
    run: melos version
    description: Bump version in all packages.

  build:
    run: melos exec -- "fvm flutter pub run build_runner build --delete-conflicting-outputs"
    description: Run `build_runner build` in all packages.

  watch:
    run: melos exec -- "fvm flutter pub run build_runner watch --delete-conflicting-outputs"
    description: Run `build_runner watch` in all packages.
